### ISSUE TITLE
[v0.4.1] Unable to work on Windows 8.1

### ISSUE THREAD

**Issue by GB-CG** [FIX94/fixGB#2]
When I try to open the program, the window appears very briefly then closes.

**Comment by FIX94** [comment]
there is no GUI or anything, its drag-and-drop your ROM of choice into the application, if it THEN still closes, it may be a incompatible memory controller, you could easly see the message it prints by just calling it via command line like "fixGB your_rom.gb" ;) Also if you want something like controller support, joy2key actually works perfectly fine with both fixNES and fixGB.

**Comment by GB-CG** [comment]
I tried typing `fixGB metroid2.gb` and got `'fixGB is not recognized as an internal or external command, operable program or batch file.`

Also, does the rom have to be in the same folder as the program? if so, that didn't work either.
Not sure if that's the correct way to it... It may be a incompatible memory controller. I do kind of remember joy2key, it's been a while. But thank you for the reminder.

**Comment by FIX94** [comment]
Well you obviously have to move the command prompt into the folder of the exe and if you are calling it via command line like that the gb rom has to be in the same folder. Also I can drag and drop "Metroid II - Return of Samus (W) [!].gb" just fine into fixGB.exe and it runs as expected, you did also extract the .dll for it and put it in the same place as the .exe right? Drag and drop really should not be this difficult...

**Comment by GB-CG** [comment]
Yes, the .dll is in the folder. Never mind, it works now. The rom was a bad dump. To be fair, I didn't know that you can drag roms to the .exe itself. Sorry about that. Thanks again! Closing.

**Comment by GB-CG** [comment]
Just a thought: Will there be a GUI in a future release? This would be ideal because than I can use it on my Mac with Wine since drag and drop is not supported on Mac Finder.

**Comment by FIX94** [comment]
I have no experience with any GUI library so thats already quite problematic.
